"""add_zoho_sign_fields_and_states

Revision ID: ed8fe2b9a6b2
Revises: 800fd3e5ff87
Create Date: 2026-05-02 10:47:08.940247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed8fe2b9a6b2'
down_revision: Union[str, Sequence[str], None] = '800fd3e5ff87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formularios', sa.Column('zoho_request_id', sa.String(), nullable=True))
    op.add_column('formularios', sa.Column('ruta_documento_firmado', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formularios', 'ruta_documento_firmado')
    op.drop_column('formularios', 'zoho_request_id')
    # ### end Alembic commands ###
